### ISSUE TITLE
Call to camera controls using variables rather than absolutes

### ISSUE THREAD

**Issue by ChrisSW58** [bitfocus/companion-module-ptzoptics-visca#27]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

It would be helpful if Companion could make calls to PTZOptics using a variable and calculation for Camera number and Preset Number. Thus I could recall a preset with (<VariableA> + 1) for Camera (<VariableB> + 1). Believe this is a Companion issue for making the call rather tag a PTZOptic request, hence posted here. This would make coding of saving and loading preset configs a lot easier.

### Usecases

Different camera presets for different types of events; different camera presets for different users with their favourite shots.

**Comment by ChrisSW58** [comment]
As I am not sure if anyone is actively looking at this, please let me explain the scenario why this would be useful to me. We have a system which uses 4 presets per camera based on the StreamDeck XL buttons (6 columns of cameras, 4 camera presets). I allow each operator to have their own set of presets, as well as the default. For that to work, I save their presets in higher preset numbers per camera and then recall them into the standard 4 presets. If instead of having to recall them and put them in the standard 1-4 presets per camera, I could call the presets directly with a variable (based on the operator), things would be so much quicker and easier. I hope this makes sense. many thanks for all your hard work.

**Comment by ploveman** [comment]
I've been working on being able to recall a preset via variable since it would simplify our church setup.  You'd still target a particular camera, would that be useful to you?  I don't think doing camera by variable would make a lot of sense from what I understand since the connection is per camera.

**Comment by ChrisSW58** [comment]
Hi there.

We are a church as well, with 6 cameras and 4 presets. Initialising the cameras (we allow operators to store their own presets) requires each camera and each preset to be configured. Currently that is 24 calls to recall their presets and 24 calls to load them into the operating presets.

If I had variables for both camera and preset, then it would be so much simpler. I know that the presets are defined in the code per camera which Companion sends to it, but logically, if you were building the call, it would be comparatively easy to use a variable to insert the camera number on that code call - as easy as to insert the variable for the preset number.

I wait in hope! 

Kind regards and many thanks,

Chris

**Comment by ploveman** [comment]
@ChrisSW58  I think targeting the camera with a variable is a larger lift than I can contemplate.  From how I read it, the way the module is built the socket from companion to the camera comes up and is maintained/reconnected via that TCP socket.  It uses that to represent status that the connection is good/healthy.  I don't know if  this module could ever support targeting a camera via a var b/c it would then have to maintain multiple connections.  @jswalden  I think has been working a a pretty major re-write (at least of how the code is organized), but believe fundamentally the nature of the connection will remain unchanged).   I still plan to continue to have a var for presets, that at least helps some.  One thing you might be able to do is to setup some buttons with conditional presses to work around the multiple camera aspect. e.g. if this expresssion is true, send preset varible to camera x.

**Comment by ChrisSW58** [comment]
Thanks for the clarification. I had thought it was simply an HTTP call with a relevant code sequence which could have the relevant code pair changed as needed.I look forward to any changes in this area. Many thanks and good luck. Kind regards,ChrisOn 26 Mar 2024, at 1:10 AM, ploveman ***@***.***> wrote:﻿
@ChrisSW58  I think targeting the camera with a variable is a larger lift than I can contemplate.  From how I read it, the way the module is built the socket from companion to the camera comes up and is maintained/reconnected via that TCP socket.  It uses that to represent status that the connection is good/healthy.  I don't know if  this module could ever support targeting a camera via a var b/c it would then have to maintain multiple connections.  @jswalden  I think has been working a a pretty major re-write (at least of how the code is organized), but believe fundamentally the nature of the connection will remain unchanged).   I still plan to continue to have a var for presets, that at least helps some.  One thing you might be able to do is to setup some buttons with conditional presses to work around the multiple camera aspect. e.g. if this expresssion is true, send preset varible to camera x.

**Comment by ploveman** [comment]
@ChrisSW58 although I don't think this module would be able to target a camera with an IP, you reminded me that PTZOptics does have an http API.  This is a VISCA module so I don't think it makes sense to move to http, but you might be able to use the generic http module to do what you want.  It appears that the URI can use variables.  Here's a reference in PTZOptics help on recalling a preset (it's OBS, but the URI concepts would be the same).  [https://help.ptzoptics.com/support/solutions/articles/13000075770-using-obs-scene-switching-to-automate-ptzoptics-preset-recall](url)  I don't know if usually things like this get their own module to simplify or other.

**Comment by ChrisSW58** [comment]
Very many thanks - much appreciated. Just need to get the time now to code and test! :)

Kind regards,

Chris

**Comment by jswalden** [comment]
@ploveman The "Recall Preset" action could accept custom input so you could specify a variable, that seems easy enough.

As long as it's one connection per camera, I agree that that extra level of option is not terribly useful.  (Especially since cameras literally must occupy different spaces, so there's no real reason why preset 17 on camera 1 should have any coordinate meaning with preset 17 on camera 2.)  But you could fake it by creating a page of "recall preset" buttons per camera, each one using the same variable to indicate which preset is desired...and then press "button x + $var" to target and press the desired button.

I'm kind of drowning in unlanded patches right now, so I think I'd like to clear some of that out first.  I'll try to get the most critical parts of that landed this week.

**Comment by ploveman** [comment]
@jswalden I have a version that would accept a variable, since I only have 2 cameras in my setup and just alternate between basically the same shot across the 2, being able to do via a variable would be helpful.  That being said I'll old off until you have whatever landed and will rework with your refactor.

**Comment by jswalden** [comment]
Fundamentally, I think this module -- consistent with standard Companion module practice -- should only work with respect to the connection/single IP/camera an action was associated with.  It is not normal for modules to maintain connections to a multiplicity of devices that it interacts with/treats parametrically -- not least because things like "connection failure" stop making sense when you have multiple connections and only some of them at a time might be in failure state.

Theoretically, if you wanted to do something like this, you might be better asking for an internal action to change the connection an action is associated with, following up on https://github.com/bitfocus/companion/pull/3110.  (But note the inherent hazards in mutation of this sort -- for example if during the actions of one button step that mutates an action's connection, another invocation of that button step is performed.

**Comment by ChrisSW58** [comment]
This is working and desired with the current system - the ability to save and recall presets using a variable. Not sure why it’s marked therefore as Not Planned

**Comment by jswalden** [comment]
> This is working and desired with the current system - the ability to save and recall presets using a variable.

Well, as I read this issue there are two halves to this request -- one to allow "Preset number" to be chosen by variable, one to select the "Camera number" the action applies to.  The first half was addressed in #53 and is what you refer to.  But second part is what is Not Planned.
