### ISSUE TITLE
Power On/Off

### ISSUE THREAD

**Issue by jmrowe504** [bitfocus/companion-module-ptzoptics-visca#4]
Unable to add custom command as it isn't working.  Command for Power On is 8x 01 04 00 02 FF. Command for Power Off is 8x 01 04 00 03 FF.

**Comment by BlakesHeaven** [comment]
It would be great to have this option :+1:

**Comment by Degeert** [comment]
Tested it and it works for me. I am new to this ...

It took a while before i understood that if the custom command is displayed in red, it will not work.
In my case i had to replace the second character (x) by the camera id number.
So instead of 8x 01 04 00 03 FF  i have typed 8**1** 01 04 00 03 FF   and bingo!



![image](https://user-images.githubusercontent.com/71590706/93709905-89691500-fb42-11ea-91aa-6b5e612422b9.png)

**Comment by JeffreyDavidsz** [comment]
I've added this option/action to the module please test, as I don't have a camera to test it on

**Comment by BlakesHeaven** [comment]
Thanks @JeffreyDavidsz .
Sorry if this is a daft question or is obvious, however, how does one update a single module in isolation before the whole Companion app is made available for download with new features?

**Comment by JeffreyDavidsz** [comment]
Unfortunate that is not possible unless you have a developer environment. In that case you can just pull the module. You can install this version and reinstall the previous one if needed. When you do that please only do so if you are already on 2.1.0 (or your database might get in trouble)

**Comment by BlakesHeaven** [comment]
Thanks for confirming,  that's fine. I'll wait.

**Comment by BlakesHeaven** [comment]
Hi, I thought I would come back on this and say that @Degeert is correct; it does work.
- Command for Power **On** is 8**x** 01 04 00 02 FF. 
- Command for Power Off is 8**x** 01 04 00 03 FF.
Replace **x** with the PTZ camera number - I have one camera so 8**1** worked for me as well.

The only thing is that the camera seems to take a little while to react. 
I am not sure if it should be instant, but it certainly seems to take a while for the camera to wakeup.
I currently have two buttons; one for ON and the other for OFF (no tach-on ticked).


There are, also, two things I am missing or am unsure of:

1. I know I can use the Toggle Latch and put the two commends on a single button, but if I do I guess I'll be **constantly** sending either signal (which ever it is latched to) - is this OK ?
2. There seems to be no signal back from the camera to indicate if the Camera is ON. I know it probably can't send a signal if it is OFF, but I really need to know if it is ON and be able to change the button colour to green when it is powered ON. Is this possible?

Please, say if this should be on a seperate Issue (or two), in which case I'll create issue(s) and edit this accordingly.

Many thanks, 
David

**Comment by jswalden** [comment]
The "Power Camera" option is in the current module in Companion releases and works fine, so I'm closing this to clear out the open issue.  (I'll rename "off" to "standby" in the UI to better reflect what it does soon, but that won't change the function or how it works.)

I think the turnaround time on going to standby and waking from it is intrinsic to the camera, not to this module, and you shouldn't do anything that depends on wakeup being especially fast.

As far as signals back from the camera go for whether it's on or off/standby -- one PTZOptics doc dated 6/25/2001 documents a `8x 09 04 00 FF` inquiry to which the response is `y0 50 0p FF` with p=2 being on, p=3 being off/standby, p=4 being "Internal Power Circuit Error".  I don't know if that applies to the latest cameras or not -- it's not in PTZOptics G3 documentation dated 10/27/2003, and I haven't tried sending it to the Move SEs I have to see if it works.

With the changes made in #33/#42 it should at least be _possible_ to send that inquiry and find out current camera state, within the camera's VISCA connection.  Exposing that as feedback or whatever is more troublesome, tho, because camera connections aren't exclusive, and I dislike the idea of exposing anything that pretends the module's one connection is the only mutator.  But perhaps something can be done to empower users to affirmatively accept that risk.  I dunno.  Anyway, that's probably a more generalized problem that shouldn't be addressed entirely one-off just for this one bit of camera state.
