### ISSUE TITLE
Cameras Randomly Disconnect

### ISSUE THREAD

**Issue by ukiews** [bitfocus/companion-module-ptzoptics-visca#62]
I've been using some Telycam PTZ cameras with this plugin for a while.
However, with the latest version, cameras randomly disconnect after some period, with following log:
![Screenshot 2024-09-09 at 10 15 58 PM](https://github.com/user-attachments/assets/351b7e8a-7122-4b3b-ad81-32a7e7512e87)

**Comment by jswalden** [comment]
Your camera is replying with a Syntax Error message, indicating a syntax error was encountered in the messages you send to the camera.  But somehow, all previous messages you've sent to the camera were fully replied to (with ACK + Completion, or with an error message).  So basically it's like the module's connected to the camera...and then out of the blue the camera says "Hey, I got a syntax error in...no command you sent at all".

Such an error response _could_ be simply logged then dropped.  But honestly, when this happens there's some possibility that there's an error in the module in handling sent commands/inquiries in some way.  And if that were the case, just dropping the error reply could easily result in the module's understanding of commands/inquiries and replies becoming desynchronized -- and the module might start thinking that commands were wrongly completed when they actually aren't.

There's also the chance that your camera sends a spurious error reply in situations where there _are_ pending commands -- and the spurious error reply gets wrongly applied against one of them.  That also would desynchronize command/reply handling.

This appears to be a bug in your camera, that can't coherently be handled because the camera is violating VISCA protocol expectations in ways that can't be recovered from.  And as it's not a PTZOptics camera, I think this module's willingness to implement VISCA meaning-violating handling has run out.  Fork the module into one specific to Telycam cameras, then implement whatever handling for this is suitable in it.
